summary: Obtener datos de un producto
tags:
- product
description: Obtiene los datos de un producto
produces:
- "application/json"
parameters:
- name: "Authorization"
  in: "header"
  required: true
  type: "string"
- name: "product_id"
  in: "path"
  required: true
  type: "string"
responses:
  200:
    description: Producto seleccionado
    schema:
      type: object
      properties:
        data:
          $ref: "#/definitions/Product"
            
        error:
          type: integer
          enum: [0, 1]

  400:
    description: El producto no existe
    schema:
      $ref: "#/definitions/Error"
  403:
    description: Acceso restringido
    schema:
      $ref: "#/definitions/Error"
