summary: Obtener la lista de los productos
security:
  - ApiKeyAuth: []
tags:
- Producto
description: Obtiene la lista de productos
produces:
- "application/json"
responses:
  200:
    description: Listado de productos
    schema:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/definitions/Product"
        error:
          type: integer
          enum: [0, 1]
  403:
    description: Acceso restringido
    schema:
      type: object
      properties:
        error:
          type: integer
          enum: [0, 1]
          example: 1
        message:
          type: string
          example: Authentication is required!

definitions:
  Error:
    type: object
    properties:
      error:
        type: integer
        enum: [0, 1]
        example: 1 
        description: "0: Existoso, 1: Ocurrio un error"
      message:
        type: string
        example: Se produjo un error
        description: Razón por la que se produjo el error
  Product:
    type: object
    required:
      - nombre
      - descripcion
      - precio
    properties:
      _id:
        type: string
        example: 5e4419383bf41d0546b5b249
      nombre: 
        type: string
        example: Coca Cola
      descripcion: 
        type: string
        example: Este producto es maravilloso
      precio: 
        type: string
        example: 1.5
      imagen: 
        type: string
        example: coca_cola.png
      tags:
        type: array
        example: [Bebida, Refresco]
          